### ISSUE TITLE
Segmentation fault on mipsel-unknown-linux-musl v1.15.3

### ISSUE THREAD

**Issue by RAX7** [shadowsocks/shadowsocks-rust#1145]
Sometimes then I trying use `sslocal` tool on wifi router it's fail

![screenshot](https://user-images.githubusercontent.com/10919192/224957322-92d3d5d0-6d9d-4bbc-8284-09e4a266494d.png)

Previous release (1.15.2) works fine, maybe a reason of this behavior is using another version of `upx` packer for current release. But I not sure.

Hardware: [ASUS RT-N16](https://openwrt.org/toh/asus/rt-n16)
OS: OpenWrt 21.02.5, r16688-fa9a932fdb

**Comment by RAX7** [comment]
@zonyitoo well I tried remove `lzma` and `best` flags, bug got same `Segmentation fault` error
https://github.com/RAX7/shadowsocks-rust/releases

**Comment by RAX7** [comment]
@zonyitoo I reverted the commit https://github.com/shadowsocks/shadowsocks-rust/commit/872e994fd1d611674d7be8d891d74d6ff3df479c and that fixed the issue. But binary size grows to 8Mb from 2.5Mb

**Comment by riKirsti** [comment]
Hi @RAX7
My hardware is [K2P](https://openwrt.org/toh/hwdata/phicomm/phicomm_k2p) and I tried this implementation on OpenWrt SNAPSHOT r22260-a7a3de5edb and OpenWrt 22.03.3, r20028-43d71ad93e both worked fine for a long time.
I also tested your configuration but didn't meet that issue.
![image](https://user-images.githubusercontent.com/81143735/225182384-343183fa-ad42-4ff3-9eaf-f9e4abf17087.png)
I noticed that your soc architecture is mipsel_74kc while mine is mipsel_24kc. Not sure this difference will cause the problem since they all belong to MIPS family.

Have you ever tried to upgrade your OpenWrt to the latest or current stable version? I didn't find any issue related to this on the [UPX Project](https://github.com/upx/upx) and [OpenWrt Project](https://github.com/openwrt/openwrt). Just wonder if upgrading OpenWrt will solve the problem.

@zonyitoo I can't find anything suspicious but I guess we could revert the [commit](https://github.com/shadowsocks/shadowsocks-rust/commit/872e994fd1d611674d7be8d891d74d6ff3df479c) for now.

**Comment by zonyitoo** [comment]
> @zonyitoo I can't find anything suspicious but I guess we could revert the [commit](https://github.com/shadowsocks/shadowsocks-rust/commit/872e994fd1d611674d7be8d891d74d6ff3df479c) for now.

Ok.

**Comment by zonyitoo** [comment]
Close it for now.

**Comment by RAX7** [comment]
@riKirsti Did you try to start `ssservice` a multiple time? I mean start process and kill it with ctrl+c and start it over and over again. Because this bug is realy randomly, maybe you just lucky.

> Have you ever tried to upgrade your OpenWrt to the latest or current stable version?

I've tried but got some issues with wifi driver on newest versions OpenWrt. That's why I'm using previous 21.02.5 version.
https://github.com/openwrt/openwrt/issues/10441
