### ISSUE TITLE
Allow keep alive all the time.

### ISSUE THREAD

**Issue by fernvenue** [shadowsocks/shadowsocks-rust#1171]
Hi, I use `tunnel` mode with `aes-256-gcm` to protect unencrypted SMB connections, but I found out that when there is no data exchange for a long time, it disconnects from the remote SMB service and tells me that the remote device is not available. After I manually select it (maybe it establishes a new connection here), it resumes normal. Can we allow an `always` or similar `keep_alive` value to be used, so that we can always keep the connection? I think this would be so useful in some `tunnel` applications.

**Comment by database64128** [comment]
> so that we can always keep the connection

This already is the behavior of shadowsocks-rust since many versions ago. What server implementation are you using?

**Comment by fernvenue** [comment]
Hi @database64128, thx for your reply, I'm using the latest version of shadowsocks-rust:

```
~# ssservice -V
shadowsocks 1.15.3
```

And could you please tell me what should I do for keep alive all the time? Maybe I need to do something in configuration file?

**Comment by database64128** [comment]
Are you using this version of shadowsocks-rust as both server and client? TCP keepalive is enabled by default with a 15s interval and idle duration since [v1.11.1](https://github.com/shadowsocks/shadowsocks-rust/releases/tag/v1.11.1). You don't have to set anything in configuration.

What SMB client and server are you using? If you are using ksmbd as the server, you might want to upgrade your kernel to at least 6.2.9. There was [this fix](https://github.com/archlinux/linux/commit/be6f42fad5f5fd1fea9d562df82c38ad6ed3bfe9) that removed the default idle timeout.

**Comment by fernvenue** [comment]
Ah thanks! That's actually fix the problem! Thx a lot :)
