### ISSUE TITLE
Add outbound interface to ACL.

### ISSUE THREAD

**Issue by fernvenue** [shadowsocks/shadowsocks-rust#1186]
Hi, I'm using shadowsocks-rust with server has multiple interfaces, and I wanna know that is there any way to set outbound rules in ACL? So that I can do some IP based or domain based access control on server side :)

**Comment by zonyitoo** [comment]
I don't think it is possible to control it via ACL rules.

**Comment by fernvenue** [comment]
Hi @zonyitoo, thanks for your reply, is there any other way to do that? Or is it posible to add this feature?

**Comment by zonyitoo** [comment]
For IP rules, you could do that easily with `iptables`.

**Comment by zonyitoo** [comment]
I understand your requirement, but currently the ACL rule is for Access Control only.

> so that we can use different IP rules for multiple shadowsocks services on same server

It is Ok via `iptables` rules, because you can set a different firewall mark with `--outbound-fwmark` for each individual instances.

> and domain based access control of course.

It would be possible to add another new file, a "route rule configuration" file. But then it will become another V2Ray. :( Why should we invent another V2Ray.

**Comment by fernvenue** [comment]
> It is Ok via `iptables` rules, because you can set a different firewall mark with `--outbound-fwmark` for each individual instances.

Ah, I see, thanks for mention that, I'm gonna try it.

> It would be possible to add another new file, a "route rule configuration" file. But then it will become another V2Ray. :( Why should we invent another V2Ray.

Yea, I agree with you, thanks for answering my questions, thank you.
