### ISSUE TITLE
Option to disable DNS cache.

### ISSUE THREAD

**Issue by fernvenue** [shadowsocks/shadowsocks-rust#1215]
Hi, I'm using shadowsocks-rust with my own local DNS server, and it does have DNS cache already, so I think maybe we can add an option to disable DNS cache for shadowsocks-rust? If shadowsocks-rust already supports this feature or I've got something wrong, please correct me, thx :)

**Comment by fernvenue** [comment]
Hi @zonyitoo, thanks for your reply, and sorry for the late response. I'm a little bit confused here. Do you mean we can't disable DNS cache? Actually, I don't have any DNS pollution issues, and trust-dns is causing me some problems. Is there any way to make shadowsocks-rust just use the system DNS directly without any changes?

**Comment by zonyitoo** [comment]
https://github.com/shadowsocks/shadowsocks-rust/blob/master/crates/shadowsocks/src/dns_resolver/trust_dns_resolver.rs#L102

You could set `cache_size = 0` right here and see if it solves your problem.

**Comment by fernvenue** [comment]
Thanks, I'll give it a shot :)

**Comment by fernvenue** [comment]
Hi @zonyitoo, I just trid https://github.com/zedifen/shadowsocks-rust/commit/9aba921a09061aa19cc0610e7be545d0bd69338d and it worked perfectly fine for me, maybe we can add a flag like `--disable-dns-cache` for this feature?

**Comment by zedifen** [comment]
Looks like shadowsocks-rust allows user to use their system's default DNS (instead of trust-dns), as described in [README - Configuration Environment Variables][readme-env]; to enable this, use `--dns "system"` [^1] together with `export SS_SYSTEM_DNS_RESOLVER_FORCE_BUILTIN=1` (to force use the `DnsResolver::System` as fallback — which [is tokio's builtin resolver][tokio-builtin-comment] — instead of trust-dns backend) [^2].

[readme-env]: https://github.com/shadowsocks/shadowsocks-rust/blob/master/README.md#environment-variables
[tokio-builtin-comment]: https://github.com/shadowsocks/shadowsocks-rust/blob/master/crates/shadowsocks/src/dns_resolver/resolver.rs#L47

[^1]: According to code at [crates/shadowsocks-service/src/config.rs#L2070](https://github.com/shadowsocks/shadowsocks-rust/blob/master/crates/shadowsocks-service/src/config.rs#L2070), this yields a `DnsConfig::System` enum. 
[^2]: When called by [crates/shadowsocks-service/src/local/mod.rs#L168](https://github.com/shadowsocks/shadowsocks-rust/blob/master/crates/shadowsocks-service/src/local/mod.rs#L168), [`build_dns_resolver`](https://github.com/shadowsocks/shadowsocks-rust/blob/master/crates/shadowsocks-service/src/dns/mod.rs#L9) returns a `None` is both are set, which makes things fall back to the default `DnsResolver::System` as in [crates/shadowsocks/src/context.rs#L39](https://github.com/shadowsocks/shadowsocks-rust/blob/master/crates/shadowsocks/src/context.rs#L39)

**Comment by zedifen** [comment]
Anyway, I also propose [a simple patch](https://github.com/shadowsocks/shadowsocks-rust/compare/master...zedifen:shadowsocks-rust:master), to allow the changing of `cache_size` in trust-dns, through command-line (as well as config file?).

**Comment by fernvenue** [comment]
Hi @zedifen, I just tested it, and `--dns-cache-size 0` worked perfectly fine for me :)

**Comment by fernvenue** [comment]
Here's how I tested it, start a pure socks server first:

```
~# ssservice local --dns-cache-size 0 --dns udp://[::1]:53 -b [::1]:1080
xxxxxxxxxxxxx INFO  shadowsocks socks TCP listening on [::1]:1080
```

Send a request to check if it works:

```
~# curl -sI https://example.com -x socks5h://[::1]:1080 | grep HTTP
HTTP/2 200
```

After that, I changed `example.com`'s resolution to `::` on my local DNS server, then:

```
~# curl -sI https://example.com -x socks5h://[::1]:1080
curl: (97) Can't complete SOCKS5 connection to example.com. (5)
```

So, it seems worked perfectly fine. @zonyitoo can we merge this change to the master branch?

**Comment by fernvenue** [comment]
Seems we can close this issue for now :)
