### ISSUE TITLE
TCP redirect couldn't get destination, peer: 192.168.33.65:55379, error: Not supported (os error 95)

### ISSUE THREAD

**Issue by kousyougi** [shadowsocks/shadowsocks-rust#1221]
I built a nightly version of shadowsocks-rust.
The TCP redirect cant not work, but the same config works fine at v1.15.3.

sslocal:
2023-06-13T17:19:59.777427317+00:00 ERROR TCP redirect couldn't get destination, peer: 192.168.33.65:55379, error: Not supported (os error 95)

**Comment by zonyitoo** [comment]
Please run `sslocal` with `strace` and get which syscall returns `ENOTSUPP`.

**Comment by zonyitoo** [comment]
Since I couldn't get feedback from the original issue owner, I could only make my guess about this error:

https://man7.org/linux/man-pages/man3/errno.3.html

Accourding to Linux's man page, `ENOTSUP` and `EOPNOTSUPP` should have the exactly the same value, so why it still reports Not Supported? Intesresting. The only way to find out is `strace` and confirm that which exactly syscall returns this error and which exactly version of kernel have this special behavior.

**Comment by zonyitoo** [comment]
Ah, I made a mistake: `ENOPROTOOPT` is not `EOPNOTSUPP`, they look quite similar!

**Comment by kousyougi** [comment]
Just tested. It worked fine. Thank you
