### ISSUE TITLE
Using Docker for multiple VPS

### ISSUE THREAD

**Issue by egasvegas1109** [shadowsocks/shadowsocks-rust#1540]
Hello, as I understand it, there is only sserver and sslocal for using docker? But why is there no ssmanager? It would be convenient to manage multiple servers at once.
I just want to conveniently deploy shadowsocks-rust on multiple VPS and am now looking for a way to do this. So far, I have come to the decision to use either docker (but not ssmanager here), or use the "main" ssmanager to manage other ssmanager on other VPS. Can you please give me some advice on this?

**Comment by zonyitoo** [comment]
1. The original PR only made `sslocal` and `ssserver` docker images.
2. `ssmanager` is not useful for most users.
3. I don't think the protocol that `ssmanager` was implemented is well designed, it was there just because shadowsocks-libev has a `ssmanager` binary. I would recommend you to implement one that could fulfill all your requirements of your usecases.
