### ISSUE TITLE
How to enable https proxy type?

### ISSUE THREAD

**Issue by hanyuwei70** [shadowsocks/shadowsocks-rust#1569]
I have found that there is not "https" type in local.
Since README says it supports https, how to enable it?

**Comment by AaronChen0** [comment]
Setting "http" in local config will handle "https" traffic too.

**Comment by zonyitoo** [comment]
What do you man https proxy? Enable a local server that provides HTTP Proxy service in HTTPS protocol (with TLS)?

That is not supported, because there is no RFC that said HTTP Proxy protocol should use HTTPS.

If you are asking how to support proxying HTTPS requests. All the `--protocol` supports HTTPS:

1. For socks (socks5, socks4a), it runs on TCP (and UDP) to establish tunnels.
2. For http, for most HTTP clients, it will use `CONNECT` method to establish a TCP tunnel, and then sends HTTPS requests in that tunnel.
3. For redir, tun, they are running on IP level, so it supports HTTPS with no doubt.

So there is nothing to "enable".

**Comment by hanyuwei70** [comment]
I am using http/https proxy for docker daemon.
docker daemon seems like only use https for image downloading and it will complain "not tls" after setting proxy address.

**Comment by zonyitoo** [comment]
This is completely not related this project. It is docker fails to download image from the address (probably blocked).
