### ISSUE TITLE
sslocal proxy error: https is not supported, consider enable it by feature "local-http-native-tls" or "local-http-rustls"

### ISSUE THREAD

**Issue by MickleWen** [shadowsocks/shadowsocks-rust#1670]
i use brew to install shadowsocks-rust, and set https_proxy=http://localhost:1080
when i use axios to request https api,  find the error

**Comment by zonyitoo** [comment]
Just like the error suggested, you should compile it with feature `local-http-native-tls` or `local-http-rustls`.

But why your client uses HTTP Proxy Protocol directly to connect https targets? For most http clients, they uses `CONNECT` to establish a TCP tunnel and then connect the https targets through this tunnel.

`CONNECT` doesn't need `local-http-native-tls` or `local-http-rustls`, which is why they are not included in the default build.

https://github.com/axios/axios/issues/925#issuecomment-513028175

It looks like it was axios' issue, which didn't support https requests to proxy properly.
