### ISSUE TITLE
File descriptor leak on Linux

### ISSUE THREAD

**Issue by cfal** [shadowsocks/shadowsocks-rust#252]
I'm running shadowsocks 1.8.11 and have also seen this in older versions.

Every week or so, I see the following error:

`thread 'main' panicked at 'create udp association: Os { code: 24, kind: Other, message: "No file descriptors available" }', /volume/src/relay/udprelay/server.rs:371:21`

I previously ran shadowsocks-libev on the same server and never encountered this problem, so believe the issue is with this implementation.

Command line:
```
ssserver --no-delay -c config.json
```

Config:
```
{
    "server": "...",
    "server_port": ...,
    "password": ".."
    "timeout": 300,
    "method": "chacha20-ietf-poly1305",
    "mode":"tcp_and_udp"
}
```

**Comment by zonyitoo** [comment]
`shadowsocks-rust` uses a cache with expiry duration. By default all UDP associations are kept for **5 minutes**, which should be the cause of your issue.

https://github.com/shadowsocks/shadowsocks-rust/blob/master/src/relay/udprelay/server.rs#L285

`shadowsocks-libev` uses a LRU with limited size. `MAX_UDP_CONN_NUM` is `512` on the server side.

https://github.com/shadowsocks/shadowsocks-libev/blob/master/src/udprelay.c#L1414

So that's why you haven't encountered this problem when you are using the `libev` version.

I personally prefer the cache with expiry duration, because you can always increase your system's file descriptor limit to hold as many UDP associations as possible.

**Comment by zonyitoo** [comment]
You may try to add a timeout in your configuration, for example:

```json
{
    "udp_timeout": 10
}
```

This will tells `ssserver` to keep idling UDP associations for **10 seconds**.

**Comment by cfal** [comment]
Thanks for the quick response. I've changed that line to initialize LruCache using with_capacity(512) to see if that solves the problem. Since it seems lru_time_cache::LruCache already supports both capacity and expiry, would a pull request to make this configurable be accepted?

**Comment by zonyitoo** [comment]
Yes, sure.

**Comment by zonyitoo** [comment]
You may need to change both server and local implementations.
