### ISSUE TITLE
一些功能提议

### ISSUE THREAD

**Issue by yiguihai** [shadowsocks/shadowsocks-rust#366]
从c版转到rust版算算也有几个月时间了，跟trojan和v2ray比优点不多功能缺陷却不少！  
对比别人只能羡慕嫉妒恨了之所以还在用只能说情怀吧。  
首先是服务端 ：
端口限速和端口连接数限制据我所知，从衍生的ssr就开始有了  
 ss从py版到c版再到rust版本都没有提供这个功能，先不说机场方面的。就是个人用户也有时候分享出账号给别人用的吧？如果没有限速和连接数限制根本逃脱不了滥用的后果。  
再一个就是服务端半残的acl控制，看日志全部都是ip地址写域名根本没用。一个ip可以对应多个域名。  
客户端：  
一个硬性缺陷就是不能像v2ray一样使用tcp传输udp。平时还没什么一到晚高峰udp丢包丢到死！为什么不能通过tcp传输呢这样就可以使用cdn中转了？我还得开两个端口一个用来传udp一个使用v2插件cdn中转。    

再吐槽一下端口实时连接人数和流量超出下线我自己还是用脚本去实现的😩 ，你可能会说用第三方工具但是可以原生实现的功能为何要这么费劲折腾呢？用了这么久给我最直观的感受就是：简陋、只适合个人使用
可以去看下[trojan-go](https://github.com/p4gefau1t/trojan-go)的介绍

**Comment by zonyitoo** [comment]
> 再一个就是服务端半残的acl控制，看日志全部都是ip地址写域名根本没用。一个ip可以对应多个域名。

Please take a look at your clients' configuration, you must have misconfigured that domain names are resolved locally.

> 端口限速和端口连接数限制据我所知

How about `ssmanager`.

> 一个硬性缺陷就是不能像v2ray一样使用tcp传输udp。平时还没什么一到晚高峰udp丢包丢到死！为什么不能通过tcp传输呢这样就可以使用cdn中转了？我还得开两个端口一个用来传udp一个使用v2插件cdn中转。

This can only be solved by redesign a new protocol.

Actually, you should transfer this issue to [shadowsocks-org](https://github.com/shadowsocks/shadowsocks-org). The shadowsocks-rust is only an implementation of shadowsocks. What you are proposing should be discussed with all members in the community and make it standarized.

This is my side-project. I couldn't implement that a lot of non-standard features that I personally don't need it in my daily life, for example, close servers by flow control, which must not be a common feature for personal users.

I am going to close this, because I can't help more about this issue. Again, please discuss it in shadowsocks-org.

**Comment by DuckSoft** [comment]
Code is speech. No code, no speech.

**Comment by yiguihai** [comment]
> Code is speech. No code, no speech.

我评论冰箱还要会制冷是吧？行吧我也懒得发到shadowsocks-org去了。ss该说再见了

**Comment by studentmain** [comment]
情怀是最廉价的，不要被情怀阻碍，要学会拥抱变化，拥抱未来。
