### ISSUE TITLE
shadowsocks package for Guix

### ISSUE THREAD

**Issue by musicsd** [shadowsocks/shadowsocks-rust#385]
The shadowsocks package does not work in Guix System, it has not been upgraded for a long time, please fix, and upgrade it. Thanks

**Comment by DuckSoft** [comment]
This is confusing. I don't see any 'Guix' 'package' in `shadowsocks-rust` release.
Clarification of your statement would help us better understand your issue.

**Comment by DuckSoft** [comment]
Did you mean this? https://guix.gnu.org/en/packages/shadowsocks-2.8.2-0.e332ec9/
This is the very old and original package of [Python implementation](https://github.com/shadowsocks/shadowsocks/), which, had ceased development since 2018. 

I have something to clarify here:
1. **It is downstream's responsibility to update and keep up with the latest version of software**. If you feel your version is lagging, please contact the downstream instead of the upstream. The upstream may not have known that there is a downstream, or they can be completely alien about the downstream ecology and cannot offer any help.
2. **The old python implementation is no longer maintained**. This means you should use some other up-to-date implementations, like `shadowsocks-rust` or `shadowsocks-go2`.
3. **You don't have to depend wholely on system packages**. If your system doesn't offer you with the package you need, you may install directly from upstream releases, or you can do it yourself. ~~Should everything fails, just give up using that system.~~

**Comment by zonyitoo** [comment]
Actually I don’t know anything about Guix. Did somebody published shadowsocks-rust onto this platform?

You should contact to the maintainer who published this package on Guix. I am not the one.

**Comment by DuckSoft** [comment]
@zonyitoo It's `shadowsocks` python and no `shadowsocks-rust`. I suggest close this issue.
![图片](https://user-images.githubusercontent.com/7822648/104798306-b67fb880-5800-11eb-8a21-790c7e0bb249.png)

**Comment by zonyitoo** [comment]
Well, yes, it is. So it is not related to this project, closing.

**Comment by musicsd** [comment]
Sorry... I asked you and the developers to package this app for Guix, and if this is difficult for you and the developers, I will package it later...

**Comment by DuckSoft** [comment]
Uh. Just do it. We'd be ready to reach out if you need any help on our side.
We're completely alien about Guix. Sorry for that.

**Comment by musicsd** [comment]
From Maxime Devos:
Guix has a package importer for rust crates:
  "guix import crate shadowsocks"

I imported the shadowsocks crate and some dependencies (see attachment).
(To build: "guix build -f d.scm")  Some dependencies are still missing,
but I hope this is enough to get you started with writing the package
definition.

Many thanks to Maxime Devos

**Comment by musicsd** [comment]
> Guix has a package importer for rust crates:
> "guix import crate shadowsocks"
> 
> I imported the shadowsocks crate and some dependencies. [[d.scm](https://files.catbox.moe/pqmgnj.scm)]
> (To build: "guix build -f d.scm") Some dependencies are still missing,
> but I hope this is enough to get you started with writing the package
> definition.

Many thanks to Maxime Devos

**Comment by musicsd** [comment]
Please reopen issue

**Comment by musicsd** [comment]
https://guix.gnu.org/cookbook/en/html_node/Packaging-Tutorial.html

https://guix.gnu.org/manual/en/html_node/Packaging-Guidelines.html

**Comment by musicsd** [comment]
Please reopen issue

**Comment by musicsd** [comment]
We've paved the way for Guix packaging as much as we can, now we need help of package developers!
Guix packaging is not a difficult task, just spend a few minutes on the links above!

**Comment by zonyitoo** [comment]
Feel free to push this forward, just package it to Guix.

**Comment by musicsd** [comment]
OK, thanks

**Comment by zonyitoo** [comment]
There is a very simple tool: https://github.com/lelongg/carguix for generating Guix `.scm` file from crates.io.

**Comment by zonyitoo** [comment]
```scheme
(define-public rust-shadowsocks-rust-1.10.2
    (package
        (name "rust-shadowsocks-rust")
        (version "1.10.2")
        (source
            (origin
                (method url-fetch)
                (uri (crate-uri "shadowsocks-rust" version))
                (file-name
                    (string-append name name "-" version ".crate"))
                (sha256
                    (base32
                        "e20eb43e8a2edaf84fcac1bf66bdeb821c9c1c7ca2a41fb8069ea36102738247"))))
        (build-system cargo-build-system)
        (home-page "https://github.com/shadowsocks/shadowsocks-rust")
        (synopsis #f)
        (description "shadowsocks is a fast tunnel proxy that helps you bypass firewalls.")
        (license "MIT")))
```
