### ISSUE TITLE
redir function seems to be broken in the latest releases

### ISSUE THREAD

**Issue by KaraRyougi** [shadowsocks/shadowsocks-rust#532]
I used to use the following command for local redir:
 `sslocal -c config.json --protocol redir`

However with the new version, I got the following error:
```
error: The following required arguments were not provided:
    --local-addr <LOCAL_ADDR>

USAGE:
    ss-local --config <CONFIG> --local-addr <LOCAL_ADDR> --protocol <PROTOCOL>

For more information try --help
```

I thought it was just a syntax change, so I tried again with  
`sslocal -c config.json local-addr 0.0.0.0:1080 --protocol redir`

However it still didn't work. Any connection would immediately halt the program:
```
2021-05-20T21:06:12.431948637+08:00 INFO  shadowsocks socks TCP listening on 0.0.0.0:1080
thread 'main' panicked at 'aborted with Address already in use (os error 98)', bin/sslocal.rs:472:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

**Comment by zonyitoo** [comment]
Please read the [v1.10.0 release note](https://github.com/shadowsocks/shadowsocks-rust/releases/tag/v1.10.0).

Since v1.10, `sslocal` supports starting multiple local instances in the same process, so the `--local-addr` and `--protocol` paramenters are for creating a new local instance.

For your case, you should put your `0.0.0.0:1080` and `redir` into `config.json`, or put all parameters in the command line option.

**Comment by KaraRyougi** [comment]
I see. So the README needs an update, especially the **Transparent Proxy Local client** section.

**Comment by zonyitoo** [comment]
You need to write your own iptables rule.
