### ISSUE TITLE
基本肯定gfw可以通过主动探测并封锁shadowsocks-rust的端口

### ISSUE THREAD

**Issue by tianlichunhong** [shadowsocks/shadowsocks-rust#549]
vps自建的shadowsocks-rust+xray-plugs， shadowsocks-rust的版本是1.11.0， xray-plugs的版本是1.4.2. 加密采用AES--GCM，xray-plugin采用tls。在这个重要的时间，VPS的端口被封了。在vps 通过systemctl status shadowsocks-rust,看到一个错误：shadowsocks-rust.service:13 Invalid URL,ignoring,xray-plugin 通过systemctl restart shadowsocks-rust，仍然没法连通（端口被封了）。重新更换端口，重启，正常使用。过一段时间，端口再次被封。
因为仅个人使用，用得很少，基本确认不是大流量引发端口被封。也确认不是终端的其他应用监测举报的。基本确认是GFW通过监测到国际可疑流量，然后使用主动探测，接着封锁端口。

**Comment by zonyitoo** [comment]
Well, let's assume there are services that blocking ports by active probling or data flow feature detection. You are running `ssserver` with plugin `xray-plugin`, then:

```
INBOUND ---> |  xray-plugin -> ssserver  | ---> OUTBOUND 
```

So the port is listened by `xray-plugin`.

1. If there are some services that detecting with active probing, then are there any chances that xray could be identified by probing? 
2. If there are some services that detecting with data flow analyzing, then are there any chances that xray's data flow has significant features that could be detected?

Any how, since `ssserver` is hiding from the `xray-plugin`, it shouldn't be its fault.

**Comment by tianlichunhong** [comment]
Yes, you are right. Maybe I need to switch back to v2ray-plugin.

**Comment by linuxbunter213** [comment]
Try the shark plugs

**Comment by maker2002** [comment]
> Yes, you are right. Maybe I need to switch back to v2ray-plugin.

使用v2ray-plugin后还有端口被墙的情况吗？最近我用xray也被墙了端口。

**Comment by AaronChen0** [comment]
I have used shadowsocks-rust + v2ray-plugin for almost 1 month. It still goes smoothly.
While without any plugins, I got port blocked within 3 days.

**Comment by maker2002** [comment]
> I have used shadowsocks-rust + v2ray-plugin for almost 1 month. It still goes smoothly.
> While without any plugins, I got port blocked within 3 days.

Is your shadowsocks-rust without any plugins,  blocked? IP or port blocked?
