### ISSUE TITLE
How often is the domain specified by sslocal updated inside the program?

### ISSUE THREAD

**Issue by 0x112** [shadowsocks/shadowsocks-rust#636]
可能描述得不太清楚，我是想问sslocal的--server-addr参数指定了域名，程序取得这个域名的ip是多久更新一次的？

举个例子：
--server-addr参数指定了ddns.example.com, 这是个动态dns域名，这时候它指向的地址是11.11.11.11，如果我更新一下dns为11.11.22.22，sslocal会什么时候使用新的地址呢？（在我的测试中似乎要重启sslocal才能生效）

**Comment by database64128** [comment]
shadowsocks-rust uses trust-dns by default, which behaves like a normal DNS resolver. It reads your system resolver config, sends queries to the name servers, caches the results with respect to the TTL of the RRs.

Make sure to set a low TTL on your domain's RRs. Make sure the configured DNS servers in your system actually respect the TTLs. Check with tools like `dig`. You can also pass `-vvvvvv` to make shadowsocks-rust print DNS related logs.

**Comment by zonyitoo** [comment]
It all depends on your domain’s TTL.

**Comment by zonyitoo** [comment]
https://github.com/bluejekyll/trust-dns/blob/04ab19ad1cba56d042b4ed41db901175d260740b/crates/resolver/src/config.rs#L731-L754

These fields is for controlling `trust-dns` how to handle records' TTLs, and they are all remain default in shadowsocks-rust, which means that the cache time is only depend on your domain record's TTL, and the number of cached domains.

**Comment by pexcn** [comment]
遇到了同样的问题，DDNS域名更新之后，TTL为300秒，而过了300秒之后，ss-rust连的仍然是旧的IP。
@zonyitoo 能重新打开这个issue吗？

**Comment by zonyitoo** [comment]
Maybe you should firstly open the debug log
and see if the upstream DNS server actually returned the correct new IP.

**Comment by pexcn** [comment]
> Maybe you should firstly open the debug log and see if the upstream DNS server actually returned the correct new IP.

我是用ss-rust本地开了个socks5端口，然后curl测试的。
刚试了好像是正常的，但似乎客户端要重新发起请求ss-rust才会重新去解析。所以想问下这个逻辑能不能改成只要DDNS域名的TTL一到期，就自动更新呢？

因为 wireguard over ss-rust(sstunnel) 的时候我发现有异常，wireguard over ss-rust 似乎建立了连接之后，就不会断开，导致DDNS更新了，仍然在使用DDNS的旧IP

**Comment by zonyitoo** [comment]
> 所以想问下这个逻辑能不能改成只要DDNS域名的TTL一到期，就自动更新呢？

I don't think this is useful. When a cached record reached its TTL deadline, next resolve call should perform an actual resolve call to the remove DNS server, based on `trust-dns`'s behavior. Refresh DNS cache actively when TTLs are reach can only help to improve resolve call's latency, but couldn't solve your actual issue.

> 因为 wireguard over ss-rust(sstunnel) 的时候我发现有异常，wireguard over ss-rust 似乎建立了连接之后，就不会断开，导致DDNS更新了，仍然在使用DDNS的旧IP

Then there is completely nothing related to DNS's cache. For TCP tunnel, when the connection is established, there is no chance to re-resolve the remote domain, because the connection is already established. For UDP tunnel, when the UDP association is established, the remote UDP socket was created and `connect()`ed to the resolved IP, which also no chance to re-resolve the remote domain.

Even as you said, the DNS cache is flushed actively, there is still no chance to call `resolve()` for your established TCP / UDP tunnels, because they are established.

**Comment by pexcn** [comment]
> Even as you said, the DNS cache is flushed actively, there is still no chance to call `resolve()` for your established TCP / UDP tunnels, because they are established.

当TTL过期时，有没有办法让 ss-rust 主动断开呢？这时候 wireguard 会自动重连的😳

**Comment by zonyitoo** [comment]
If that happens, connections will all be disconnected every 300s, which should not be the expected behavior for most users.

**Comment by pexcn** [comment]
> If that happens, connections will all be disconnected every 300s (for most domain's TTL, even shorter), which should not be the expected behavior for most users.

暂时用 [gost](https://github.com/go-gost/gost) 端口转发解决了，用着似乎正常，先观察几天看看
