### ISSUE TITLE
Youtube buffers a lot when connected to proxy on my phone

### ISSUE THREAD

**Issue by DUOLabs333** [shadowsocks/shadowsocks-rust#707]
I'm connected to my proxy from my phone using SagerNet (at least until it breaks again :) ), and there's been this problem that Youtube buffers a lot. This does not happen on my laptop which is also connected to the proxy. I have set `nofile` to `1024` because of memory issues, so that may be part of the problem.

**Comment by zonyitoo** [comment]
1. Did you see any errors like: `Too Many Open Files`? If not, then there is nothing related to `nofile`.
2. Did you see any useful error logs when you see this problem?
3. Did you check your connectivity between clients and servers when you see this problem?

We will continue our discussion only when you have found useful details about where the problem actually located.

**Comment by DUOLabs333** [comment]
I don't see anything out of the ordinary. Though, SagerNet stopped working at this time, so I can't test it without reinstalling. However, concerning that problem, I found this: when I try connect to resolve something that's only on my personal DNS, I get 
```
created udp association for 192.168.1.90:43400 <-> 127.0.0.1:2014 (proxied) with ConnectOpts { fwmark: None, bind_local_addr: None, bind_interface: None, tcp: TcpSocketOpts { send_buffer_size: None, recv_buffer_size: None, nodelay: false, fastopen: false, keepalive: Some(15s) } }
```
, while for others I get

```
 DEBUG [109755:281472841870944] [shadowsocks_service::local::utils] established tcp tunnel 192.168.1.90:39494 <-> 44.240.200.14:443 through sever 127.0.0.1:2014 (outbound: 127.0.0.1:2014)
 ```
Connecting to a service on my server's localhost through `0.0.0.0` gives me no log.

**Comment by zonyitoo** [comment]
```
created udp association for 192.168.1.90:43400 <-> 127.0.0.1:2014 (proxied)
```

It created a new UDP association with destination `127.0.0.1:2014`. This is already a resolved IP. If I understand correctly, you may want it to be resolved on the remote server (`ssserver`), but currently it is already resolved on the client (SagerNet).

```
established tcp tunnel 192.168.1.90:39494 <-> 44.240.200.14:443
```

Local server established a TCP tunnel to `44.240.200.14:443`, which is already resolved by client.

I think there should be an issue that you client (SagerNet in your case) resolves the domain names to IP and then sends them to `sslocal` for tunneling. So I suspect that if the domain names resolves to localhosts, then SagerNet may not make the request to `sslocal` because it may realize that it is a localhost address.

**Comment by DUOLabs333** [comment]
It goes away if I completely reinstall it (not saving user data), so it's likely a variable that gets changed. Which variable, is the question.

**Comment by zonyitoo** [comment]
Then you should make an issue to SagerNet. I can't do anything here because I don't have an Android phone.

**Comment by DUOLabs333** [comment]
Of course, the buffering still happens -- if you don't set a `max connections` in the config, no maximum is set, right?

**Comment by zonyitoo** [comment]
Yes.
