### ISSUE TITLE
这段代码判断假阳性，导致本该直连的请求通过代理来访问

### ISSUE THREAD

**Issue by dev4u** [shadowsocks/shadowsocks-rust#710]
https://github.com/shadowsocks/shadowsocks-rust/blob/9b33ffca5dbe145af64c8708eb52d854f05cb4c2/crates/shadowsocks-service/src/local/dns/server.rs#L354-L359

这段代码在这种情况会处理错误：
当前模式：bypass_all，如果查询一个并不在proxy_list或者bypass_list的域名，例如ipip.net，代码跑完check_name_in_proxy_list后返回的结果是None。最后的结果是，访问ipip.net要通过代理进行访问。这明显不符合用户设置的规则（应该通过直连访问）。
代码应该是这样才符合逻辑：
```rust
if result.is_none() && acl.is_ip_empty() && acl.is_host_empty() {
    Some(acl.is_default_in_proxy_list())
} else if result.is_none() {
    Some(acl.is_default_in_proxy_list())
} else {
    result
}
```

**Comment by zonyitoo** [comment]
```rust
acl.is_ip_empty() && acl.is_host_empty()
```

means there is nothing configured in the ACL list (both IPv4 & IPv6 & Host rules are empty).

So, if the domain name is not configured in ACL list (which will always be true if Host rules are empty), then we should follow the default rule by `acl.is_default_in_proxy_list()`.

On the otherhand, if the domain name is configured in the ACL list, then it will go to the `else` block, which will be evaluated to `result`, the result that the domain name should be proxied or not.

> 当前模式：bypass_all，如果查询一个并不在proxy_list或者bypass_list的域名，例如ipip.net，代码跑完check_name_in_proxy_list后返回的结果是None。最后的结果是，访问ipip.net要通过代理进行访问。这明显不符合用户设置的规则（应该通过直连访问）。

Well then, `ipip.net` is not in ACL list, so `check_name_in_proxy_list("ipip.net")` evaluates to `None`. But since `acl.is_ip_empty() && acl.is_host_empty()` is false, then it will falls to the `else` part, evaluates to `result`, which is `None`.

Your solution could simplified to:

```rust
result.or_else(|| Some(acl.is_default_in_proxy_list()))
```

This is completely wrong. If you read the code carefully, you may find:

https://github.com/shadowsocks/shadowsocks-rust/blob/9b33ffca5dbe145af64c8708eb52d854f05cb4c2/crates/shadowsocks-service/src/local/dns/server.rs#L518-L530

If `should_forward_by_query` returns `None`, then it will try to check both local and remote DNS response and see if we should trust and use the local one. In your case, `ipip.net` eventually uses the remote DNS reponse, then 

https://github.com/shadowsocks/shadowsocks-rust/blob/9b33ffca5dbe145af64c8708eb52d854f05cb4c2/crates/shadowsocks-service/src/local/dns/server.rs#L532-L539

must have evaluated to `None`, which leads to the call of `should_forward_by_response` with the local DNS respond returns `false`.

So you are in a completely wrong direction and providing a completely wrong solution.

**Comment by dev4u** [comment]
你的意思是，如果ipip.net没有在acl里，就会通过remote dns来解析地址？
ipip.net通过远端服务器来解析，打开页面显示的是远端ip，但我希望显示本地的ip（意思是不希望通过代理访问ipip.net）。
我需要对这个域名，增加一条规则直连吗？

**Comment by zonyitoo** [comment]
If a host is not in ACL list, and ACL list is not empty, then it will try to resolve it from both local & remote DNS.

When receives the local DNS respond, it will evaluate the respond with `should_forward_by_response` and see if we should use it or wait for the remote DNS respond.

In your case, the `should_forward_by_response` checked the local DNS respond and decided not to use it.

**Comment by zonyitoo** [comment]
> 我需要对这个域名，增加一条规则直连吗？

Yes.

**Comment by dev4u** [comment]
> > 我需要对这个域名，增加一条规则直连吗？
> 
> Yes.

但是我当前用的是bypass_all，那bypass_all又代表了什么呢？

**Comment by zonyitoo** [comment]
`bypass_all` is one of the value of `acl.is_default_in_proxy_list()`.

**Comment by dev4u** [comment]
我理解的是，bypass_all表示不在proxy_list里设置的域名、ip，就走直连。
现在的情况是，我用bypass_all模式，ipip.net也没设置在proxy_list里，但却走了代理。

**Comment by zonyitoo** [comment]
If there is no rule in the ACL file, then the `bypass_all` will work. The file content should be like this:

```ini
[bypass_all]

# Yes, there is no rule configured
```

The design of the local DNS is to resolve domain names from both local and remote DNS servers and then use the ACL rules to judging whether we should trust and use the local DNS respond (may have been polluted).

So all the domain names will be resolved by both local and remote DNS servers, except those that are explicitly configured to bypass or proxy.

**Comment by dev4u** [comment]
虽然我对这样的设计，没太多想法。但如果说为了解决dns投毒而设计成这样，那我不认为这样做是有效的。正如我说的那个ipip.net，就相当于被“投毒”了，不是吗？
而且，只要那个域名，同时做了境内、外的分流，可能被代理到境外的站点（说明：这点暂未经过充分的测试）。

或许这也说明了，为什么shadowsocks-android不开[分应用vpn]，有部分国内的app会访问异常。

**Comment by zonyitoo** [comment]
cc @madeye @Mygod

**Comment by Mygod** [comment]
As far as I'm concerned everything seems to be working as intended.

**Comment by dev4u** [comment]
> As far as I'm concerned everything seems to be working as intended.

@Mygod 
现在的问题在，acl模式是bypass_all，有一域名没有存在于bypass_list、proxy_list中。这个域名是应该走直连？还是走代理？可以确认，这个域名并没有被投毒。

**Comment by Mygod** [comment]
In that case, both DNS queries will be sent. If all IPs in local DNS response are matched by `proxy_list`, the query will be directed to remote, otherwise it will be bypassed.

See: https://github.com/shadowsocks/shadowsocks-rust/blob/401f558459273b8af259f535bdf0c9a58927d46a/crates/shadowsocks-service/src/local/dns/server.rs#L419

**Comment by database64128** [comment]
Just use V2Ray if you want a good routing experience. 😄

**Comment by dev4u** [comment]
> Just use V2Ray if you want a good routing experience. 😄

嗯，v2ray系列的路由配置是真的很强大，这应该是毫无疑问的。问题他的配置也真的是冗杂。

**Comment by dev4u** [comment]
> In that case, both DNS queries will be sent. If all IPs in local DNS response are matched by `proxy_list`, the query will be directed to remote, otherwise it will be bypassed.
> 
> See: https://github.com/shadowsocks/shadowsocks-rust/blob/401f558459273b8af259f535bdf0c9a58927d46a/crates/shadowsocks-service/src/local/dns/server.rs#L419

@zonyitoo mygod的描述就是按照我说的那种情形处理。

**Comment by zonyitoo** [comment]
I don't think so.

**Comment by dev4u** [comment]
> I don't think so.
> 
> > In that case, both DNS queries will be sent. 
> 
> > If all IPs in local DNS response are matched by `proxy_list`, the query will be directed to remote, otherwise it will be bypassed.
> 
> Did you verified that the resolved IP of `ipip.net` is in your `proxy_list`?

我确信ipip.net不在proxy_list或者bypass_list列表中。

**Comment by zonyitoo** [comment]
Did you verified that the **resolved IP** of ipip.net is in your `proxy_list`?

**Comment by dev4u** [comment]
这个可以确认。因为我用的规则模式是gfwlist，当中的数据是从`github.com/NateScarlet/gfwlist.acl/master/gfwlist.acl`同步过来。proxy_list里面，除了tg的cidr外，没有其他的ip规则。

**Comment by Mygod** [comment]
I don't understand. Is there an issue or is this simply a generic question? What's your (relevant) acl config? What did you expect to see? What did you observe?

**Comment by zonyitoo** [comment]
> I don't understand. Is there an issue or is this simply a generic question? What's your (relevant) acl config? What did you expect to see? What did you observe?

Correct me if I am wrong:

1. Making a DNS query of `ipip.net`
2. `ipip.net` is not configured in the ACL list, rules are: https://github.com/NateScarlet/gfwlist.acl/blob/master/gfwlist.acl
3. Observed: `ipip.net` is actually resolved with the remote DNS
4. Expected: `ipip.net` should be resolved with the local DNS

**Comment by zonyitoo** [comment]
[The ACL rules](https://github.com/NateScarlet/gfwlist.acl/blob/master/gfwlist.acl) contains only regex patterns (host rules), so if `ipip.net` is not explicitly configured in `bypass_list`, then the query will be sent to both local and remote DNS servers. 

https://github.com/shadowsocks/shadowsocks-rust/blob/5dacd16040b5bf64c2afb23a2633da24e2dbff83/crates/shadowsocks-service/src/local/dns/server.rs#L367-L446

When receiving respond from the local server, it will check it with the `should_forward_by_response`.

Since your ACL rules didn't contain any IP rules, then you should add some logs around `should_forward_by_response` and see which branch it was running and what does it evaluated.

**Comment by dev4u** [comment]
不好意思，现在才回复。

3. Observed: ipip.net is actually resolved with the remote DNS
4. Expected: ipip.net should be resolved with the local DNS

这里应该是期待通过直连访问ipip.net，实际是通过代理访问这个网站。

`should_forward_by_response`这个方法加日志，这个我回去试试。
