### ISSUE TITLE
Message too long (os error 90)

### ISSUE THREAD

**Issue by Malayke** [shadowsocks/shadowsocks-rust#897]
I'm using tunnel mode to connect to an OpenVPN server
```
./sslocal -V
shadowsocks 1.15.0-alpha.5
```

start command
```
./sslocal --protocol tunnel -b "127.0.0.1:1194" -f "REDACKED:1194" -s "REDACKED:1234" -m aes-256-gcm -k REDACKED -U -v --udp-max-associations 1024 --udp-timeout 60 --nofile 10240
```
then OpenVPN connect to 127.0.0.1:1194, connect successful

but I do some stuff and got time out, the log said:
```
2022-07-16T07:08:50.394619532-04:00 DEBUG [68046:140393368086080] [shadowsocks_service::local::net::udp::association] 127.0.0.1:58618 -> REDACKED:1194 (proxied) sending 1428 bytes failed, error: Message too long (os error 90)
```
after searching existing issues, add additional args like `--udp-max-associations 1024 --udp-timeout 60 --nofile 10240`

but the error still exist

**Comment by database64128** [comment]
IP fragmentation does not reliably work over the internet. And it absolutely destroys throughput. That's why I asked the developer to disable IP fragmentation for Shadowsocks packets.

You should calculate and specify the tunnel MTU with `--tun-mtu` (https://github.com/OpenVPN/openvpn/blob/master/doc/man-sections/vpn-network-options.rst), or configure TCP MSS clamping with `--mss-fix` (https://github.com/OpenVPN/openvpn/blob/master/doc/man-sections/link-options.rst). If you are not familiar with MTU calculations, just set any of these to a lower value like 1300.

**Comment by zonyitoo** [comment]
> Message too long (os error 90)

is `EMSGSIZE`, the packet is larger than MTU. You should configure and lower the MTU size of your OpenVPN.

**Comment by Malayke** [comment]
@database64128 @zonyitoo  I'm solving my problem after decreasing the MTU size via `--tun-mtu` flag, thank you guys
