### ISSUE TITLE
xbox 测试多人连线时丢包 100%

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-rust#949]
![photo_2022-09-25_17-33-29](https://user-images.githubusercontent.com/4590439/192137132-6329bd23-32a2-4444-91b8-1fc75ceda244.jpg)

现象：
使用 v1.15.0-alpha.8 时, 在 xbox 测试多人连线的时候会连不通，显示丢包 100%. 请问是 ss-rust 不支持 FULLCONE NAT 的问题吗？

补充：
在使用 v1.14.3 的时候，在服务端做了以下设置是能通过 xbox 的多人连线测试的；但是同样的设置，在 v1.15.0-alpha.8 却不行。
```sh
echo 1 > /proc/sys/net/ipv4/ip_no_pmtu_disc
```

**Comment by pexcn** [comment]
关联 issue: https://github.com/shadowsocks/shadowsocks-libev/issues/361

**Comment by zonyitoo** [comment]
It is fullcone NAT. You can verify that in code.

**Comment by database64128** [comment]
This test probably tests some edge cases with large packets. Your multiplayer games should play just fine. Just ignore the test result. And don't mess with `sys/net/ipv4/ip_no_pmtu_disc`.

Your issue is related to commit be518cedbb97462ca29651ddaf633cfed30e7000, which was requested by me. Disabling IP fragmentation ensures that protocols using [DPLPMTUD](https://www.ietf.org/rfc/rfc8899.html) can probe the correct MTU, which is crucial for throughput and latency, since fragmented IP packets can be flaky over the Internet.

**Comment by zonyitoo** [comment]
I tried with Nintendo's Switch, and it showed NAT Type: A, which is Fullcone.

**Comment by pexcn** [comment]
感谢各位大佬解答😁，我决定把 ip_no_pmtu_disc 关闭了

**Comment by jelly21fish** [comment]
@pexcn 大佬您好，我的测试结果也显示丢包100%，您也还是如此吗？请问是不是忽略即可？我的多人联机有时也会联不通，但这是否与这项测试无关，而只是与线路有关？

**Comment by pexcn** [comment]
具体忘记了，保持系统的默认设置就行，显示100%丢包实际不影响使用
