### ISSUE TITLE
Cannot use login password for 2022-blake3-aes-256-gcm/2022-blake3-chacha20-poly1305

### ISSUE THREAD

**Issue by zlibdot** [shadowsocks/shadowsocks-rust#969]
I was using very long alphanumeric password (>1000) with `chacha20-oietf-poly1305`.

And when i switched encryption method to `2022-blake3-*` your software terminated with "`expected 32 length`". SSServer start working after I set base64 encoded 32-length password (`atob('32 length alphanumeric')`).

## Expected

Let user to use non-base64 encoded raw password with unknown length.
Why limit to only 32 string?

## Currently

SSServer insist on `32 length` `base64 encoded` string.

**Comment by database64128** [comment]
> Let user to use non-base64 encoded raw password with unknown length.

Why do you need this? To have a false sense of security?

**Comment by zonyitoo** [comment]
The length of password is defined by the cryptographic algorithm. For old methods, we will use a key derivation method to standardize your password, in this case, 32-bytes length.

It is quite unnecessary to make a very very long password.

**Comment by zonyitoo** [comment]
Definition of CHACHA20-POLY1305: https://en.wikipedia.org/wiki/ChaCha20-Poly1305

> But the long password is always better (harder to crack)

Well, this is correct, but this is not the reason for you to define a password longer than the length of key of the cryptocraphic algorithm itself.

> Okay if this is true, why I can add infinite alphanumeric into the UI (androidapp)?

If you are talking about shadowsocks-android, current support of 2022 ciphers are still experimental, and older ciphers (stream, AEAD) have a builtin KDF to unfiy your password to the expected key length.

**Comment by database64128** [comment]
Shadowsocks 2022's session keys are derived using BLAKE3's key derivation mode, which expects randomly-generated keys, not passwords. You can easily generate a 32-byte random key with `openssl rand -base64 32`.

**Comment by zonyitoo** [comment]
> But the long password is always better (harder to crack)

On the other hand, the complexity of password should be the most factor to make it hard to crack. For example, even you make a password 1024 bytes length, but it only contains '0'.

Some modern softwares, like WireGuard, requires the same base64 encoded key and provides a `wg genkey` to help users to generate a secured key. https://www.wireguard.com/quickstart/

Since it is base64 encoded, users cannot run the tunnel with a simple password unless they intended to do so, for example, hand writing a password with only As, `AAAAAAAAAAAAAA=` (a valid password which are zeros).

For experienced user, it is very easy to generate a base64 encoded password with various tools, like `wg genkey`, or `openssl rand`. But for newbees, this would forbids them to use simple passwords and make their tunnels vulnerable.

**Comment by zonyitoo** [comment]
`ssservice genkey` have been added on the master branch for helping users to generate a valid key for specific method.
