### ISSUE TITLE
[Enhancement] Is fake http server useful?

### ISSUE THREAD

**Issue by pedia** [shadowsocks/shadowsocks-rust#984]
First start `ssserver` on a fresh new node:
- listen on port 80
- with `strace` attached

I noticed the wall fetch http `GET /`, so my question is:

Is fake http server useful?

**Comment by database64128** [comment]
> I noticed the wall fetch http

The GFW doesn't do this. It's just random probes on the Internet.

**Comment by pedia** [comment]
> The GFW doesn't do this. It's just random probes on the Internet.
Yes before today.

I noticed this only recently.

**Comment by database64128** [comment]
> I noticed this only recently.

Interesting. Well, if you really want to know, my implementation has this [unsafe fallback](https://github.com/database64128/shadowsocks-go#3-unsafe-fallback) feature, where you can forward invalid requests to your specified address.

**Comment by zonyitoo** [comment]
Since you are listening 80, I believe it was more likely some spiders were crawing your server.

You may try to listen 22, and you will see more robots.

If you actually want to test if there is any security probing, just run a honeypot program on a random port, and then send a tcp/udp request to this port and see if there are any subsequences replay requests or probing requests received from this port.
